# Generated by Django 6.0.3 on 2026-04-16 04:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discogs_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('styles', models.JSONField(blank=True, default=list)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('tracklist', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='api.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'album')},
            },
        ),
        migrations.CreateModel(
            name='ListeningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pre_emotion', models.CharField(choices=[('stressed', 'Stressed'), ('happy', 'Happy'), ('tired', 'Tired'), ('neutral', 'Neutral'), ('calm', 'Calm'), ('sad', 'Sad')], max_length=100)),
                ('post_emotion', models.CharField(choices=[('stressed', 'Stressed'), ('happy', 'Happy'), ('tired', 'Tired'), ('neutral', 'Neutral'), ('calm', 'Calm'), ('sad', 'Sad')], max_length=100)),
                ('side_a_duration', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5999)])),
                ('side_b_duration', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5999)])),
                ('day_of_week', models.IntegerField()),
                ('hour_of_day', models.IntegerField()),
                ('month', models.IntegerField(default=1)),
                ('weather', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, max_length=50, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.album')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discogs_username', models.CharField(max_length=255, unique=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoodTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(choices=[('stressed', 'Stressed'), ('happy', 'Happy'), ('tired', 'Tired'), ('neutral', 'Neutral'), ('calm', 'Calm'), ('sad', 'Sad')], max_length=100)),
                ('count', models.IntegerField(default=1)),
                ('collection_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_tags', to='api.collectionentry')),
            ],
            options={
                'unique_together': {('collection_entry', 'emotion')},
            },
        ),
    ]
