# Generated by Django 5.2.12 on 2026-03-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listeningsession',
            old_name='current_emotion',
            new_name='post_emotion',
        ),
        migrations.RenameField(
            model_name='listeningsession',
            old_name='target_emotion',
            new_name='pre_emotion',
        ),
        migrations.AddField(
            model_name='listeningsession',
            name='side_a_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listeningsession',
            name='side_b_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listeningsession',
            name='day_of_week',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listeningsession',
            name='hour_of_day',
            field=models.IntegerField(),
        ),
    ]
