# Generated by Django 6.0.3 on 2026-04-05 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_current_emotion_listeningsession_post_emotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='album',
            name='styles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='album',
            name='tracklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listeningsession',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='MoodTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=1)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_tags', to='api.album')),
            ],
            options={
                'unique_together': {('album', 'emotion')},
            },
        ),
    ]
