# Generated by Django 6.0.3 on 2026-04-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_album_genres_album_styles_album_tracklist_album_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningsession',
            name='post_emotion',
            field=models.CharField(choices=[('stressed', 'Stressed'), ('happy', 'Happy'), ('tired', 'Tired'), ('anxious', 'Anxious'), ('neutral', 'Neutral'), ('calm', 'Calm'), ('energized', 'Energized'), ('focused', 'Focused'), ('sad', 'Sad')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listeningsession',
            name='pre_emotion',
            field=models.CharField(choices=[('stressed', 'Stressed'), ('happy', 'Happy'), ('tired', 'Tired'), ('anxious', 'Anxious'), ('neutral', 'Neutral'), ('calm', 'Calm'), ('energized', 'Energized'), ('focused', 'Focused'), ('sad', 'Sad')], max_length=100),
        ),
        migrations.AlterField(
            model_name='moodtag',
            name='emotion',
            field=models.CharField(choices=[('stressed', 'Stressed'), ('happy', 'Happy'), ('tired', 'Tired'), ('anxious', 'Anxious'), ('neutral', 'Neutral'), ('calm', 'Calm'), ('energized', 'Energized'), ('focused', 'Focused'), ('sad', 'Sad')], max_length=100),
        ),
    ]
