# Generated by Django 6.0.3 on 2026-04-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningsession',
            name='weather',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listeningsession',
            name='post_emotion',
            field=models.CharField(choices=[('stressed', 'Stressed'), ('happy', 'Happy'), ('tired', 'Tired'), ('neutral', 'Neutral'), ('calm', 'Calm'), ('sad', 'Sad')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listeningsession',
            name='pre_emotion',
            field=models.CharField(choices=[('stressed', 'Stressed'), ('happy', 'Happy'), ('tired', 'Tired'), ('neutral', 'Neutral'), ('calm', 'Calm'), ('sad', 'Sad')], max_length=100),
        ),
        migrations.AlterField(
            model_name='moodtag',
            name='emotion',
            field=models.CharField(choices=[('stressed', 'Stressed'), ('happy', 'Happy'), ('tired', 'Tired'), ('neutral', 'Neutral'), ('calm', 'Calm'), ('sad', 'Sad')], max_length=100),
        ),
    ]
