# Generated by Django 6.0.3 on 2026-04-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_collectionentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningsession',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
