# Generated by Django 6.0.3 on 2026-04-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_listeningsession_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningsession',
            name='notes',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
