# Generated by Django 6.0.3 on 2026-04-14 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_listeningsession_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningsession',
            name='side_a_duration',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5999)]),
        ),
        migrations.AlterField(
            model_name='listeningsession',
            name='side_b_duration',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5999)]),
        ),
    ]
